# Buildpacks to include in builder
[[buildpacks]]
id = "samples/java-maven"
version = "0.0.1"
uri = "../../buildpacks/java-maven"

[[buildpacks]]
id = "samples/kotlin-gradle"
version = "0.0.1"
uri = "../../buildpacks/kotlin-gradle"

[[buildpacks]]
id = "samples/ruby-bundler"
version = "0.0.1"
uri = "../../buildpacks/ruby-bundler"

[[buildpacks]]
uri = "docker://cnbs/sample-package:hello-universe"

# Order used for detection
[[order]]
[[order.group]]
id = "samples/java-maven"
version = "0.0.1"

[[order]]
[[order.group]]
id = "samples/kotlin-gradle"
version = "0.0.1"

[[order]]
[[order.group]]
id = "samples/ruby-bundler"
version = "0.0.1"

[[order]]
[[order.group]]
id = "samples/hello-universe"
version = "0.0.1"

#This samples shows how to retain backwards compatibility by including both images and stacks
# Images that will be used the builder 
[build]
image = "cnbs/sample-img-build:jammy"

[run]
[run.images]
image = "cnbs/sample-img-run:jammy"

# Stack that will be used by the builder on older platforms that do not recognize the images
[stack]
id = "io.buildpacks.samples.stacks.jammy"
run-image = "cnbs/sample-stack-run:jammy"
build-image = "cnbs/sample-stack-build:jammy"
