# Buildpacks to include in builder
[[buildpacks]]
id = "samples/java-maven"
version = "0.0.2"
uri = "../../buildpacks/java-maven"

[[buildpacks]]
id = "samples/kotlin-gradle"
version = "0.0.2"
uri = "../../buildpacks/kotlin-gradle"

[[buildpacks]]
id = "samples/ruby-bundler"
version = "0.0.1"
uri = "../../buildpacks/ruby-bundler"

[[buildpacks]]
uri = "docker://cnbs/sample-package:hello-universe"

# Order used for detection
[[order]]
[[order.group]]
id = "samples/java-maven"
version = "0.0.2"

[[order]]
[[order.group]]
id = "samples/kotlin-gradle"
version = "0.0.2"

[[order]]
[[order.group]]
id = "samples/ruby-bundler"
version = "0.0.1"

[[order]]
[[order.group]]
id = "samples/hello-universe"
version = "0.0.1"

# Base images used to create the builder
[build]
image = "cnbs/sample-base-build:noble"
[run]
[[run.images]]
image = "cnbs/sample-base-run:noble"

# Stack (deprecated) used to create the builder
[stack]
id = "io.buildpacks.samples.stacks.noble"
build-image = "cnbs/sample-base-build:noble"
run-image = "cnbs/sample-base-run:noble"
