# Buildpacks to include in builder
[[buildpacks]]
id = "samples/java-maven"
version = "0.0.3"
uri = "../../buildpacks/java-maven"

[[buildpacks]]
id = "samples/kotlin-gradle"
version = "0.0.3"
uri = "../../buildpacks/kotlin-gradle"

[[buildpacks]]
id = "samples/ruby-bundler"
version = "0.0.2"
uri = "../../buildpacks/ruby-bundler"

[[buildpacks]]
uri = "docker://cnbs/sample-package:hello-universe"

# Order used for detection
[[order]]
[[order.group]]
id = "samples/java-maven"
version = "0.0.3"

[[order]]
[[order.group]]
id = "samples/kotlin-gradle"
version = "0.0.3"

[[order]]
[[order.group]]
id = "samples/ruby-bundler"
version = "0.0.2"

[[order]]
[[order.group]]
id = "samples/hello-universe"
version = "0.0.2"

# Base images used to create the builder
[build]
image = "cnbs/sample-base-build:noble"
[run]
[[run.images]]
image = "cnbs/sample-base-run:noble"

[[targets]]
arch = "amd64"
os = "linux"

[[targets]]
arch = "arm64"
os = "linux"
