# Buildpacks to include in builder
[[buildpacks]]
id = "samples/java-maven"
version = "0.0.1"
uri = "../../buildpacks/java-maven"

[[buildpacks]]
id = "samples/kotlin-gradle"
version = "0.0.1"
uri = "../../buildpacks/kotlin-gradle"

[[buildpacks]]
uri = "docker://cnbs/sample-package:hello-universe"

[[buildpacks]]
id = "samples/hello-extensions"
version = "0.0.1"
uri = "../../buildpacks/hello-extensions"

# Extensions to include in builder
[[extensions]]
id = "samples/tree"
version = "0.0.1"
uri = "../../extensions/tree"

[[extensions]]
id = "samples/curl"
version = "0.0.1"
uri = "../../extensions/curl"

# Order used for detection (buildpacks)
[[order]]
[[order.group]]
id = "samples/hello-extensions"
version = "0.0.1"

[[order]]
[[order.group]]
id = "samples/java-maven"
version = "0.0.1"

[[order]]
[[order.group]]
id = "samples/kotlin-gradle"
version = "0.0.1"

[[order]]
[[order.group]]
id = "samples/hello-universe"
version = "0.0.1"

# Order used for detection (extensions)
[[order-extensions]]
[[order-extensions.group]]
id = "samples/tree"
version = "0.0.1"

[[order-extensions.group]]
id = "samples/curl"
version = "0.0.1"

# Images that will be used by the builder
[build]
image = "cnbs/sample-img-build:alpine"


[run]
[[run.images]]
image = "cnbs/sample-img-run:alpine"

