# Buildpacks to include in builder
[[buildpacks]]
id = "samples/java-maven"
version = "0.0.2"
uri = "../../buildpacks/java-maven"

[[buildpacks]]
id = "samples/kotlin-gradle"
version = "0.0.2"
uri = "../../buildpacks/kotlin-gradle"

[[buildpacks]]
uri = "docker://cnbs/sample-package:hello-universe"

[[buildpacks]]
id = "samples/hello-extensions"
version = "0.0.1"
uri = "../../buildpacks/hello-extensions"

# Extensions to include in builder
[[extensions]]
id = "samples/vim"
version = "0.0.1"
uri = "../../extensions/vim"

[[extensions]]
id = "samples/curl"
version = "0.0.1"
uri = "../../extensions/curl"

[[extensions]]
id = "samples/cowsay"
version = "0.0.1"
uri = "../../extensions/cowsay"

# Order used for detection (buildpacks)
[[order]]
[[order.group]]
id = "samples/hello-extensions"
version = "0.0.1"

[[order]]
[[order.group]]
id = "samples/java-maven"
version = "0.0.2"

[[order]]
[[order.group]]
id = "samples/kotlin-gradle"
version = "0.0.2"

[[order]]
[[order.group]]
id = "samples/hello-universe"
version = "0.0.1"

# Order used for detection (extensions)
[[order-extensions]]
[[order-extensions.group]]
id = "samples/vim"
version = "0.0.1"

[[order-extensions.group]]
id = "samples/curl"
version = "0.0.1"

[[order-extensions.group]]
id = "samples/cowsay"
version = "0.0.1"

# Base images used to create the builder
[build]
image = "cnbs/sample-base-build:alpine"
[run]
[[run.images]]
image = "cnbs/sample-base-run:alpine"

# Stack (deprecated) used to create the builder
[stack]
id = "io.buildpacks.samples.stacks.alpine"
build-image = "cnbs/sample-base-build:alpine"
run-image = "cnbs/sample-base-run:alpine"
