# Buildpacks to include in builder
[[buildpacks]]
uri = "docker://cnbs/sample-package:hello-universe-windows"

# Order used for detection
[[order]]
[[order.group]]
id = "samples/hello-universe-windows"
version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.samples.stacks.nanoserver-2022"
run-image = "cnbs/sample-stack-run:nanoserver-2022"
build-image = "cnbs/sample-stack-build:nanoserver-2022"
