ARG base_image
FROM ${base_image}
ARG build_id=0

LABEL io.buildpacks.rebasable=true

# TODO: replace with real package
RUN echo
# RUN curl -L https://example.com/mypkg-install | sh # installs to /opt
