# Buildpack API version
api = "0.10"

# Extension ID and metadata
[extension]
id = "samples/vim"
version = "0.0.1"
name = "Vim Extension"
homepage = "https://github.com/buildpacks/samples/vim/main/extensions/vim"
description = "A simple extension that installs vim on the builder image"
