# Buildpack API version
api = "0.9"

# Buildpack ID and metadata
[buildpack]
id = "samples/batch-script"
version = "0.0.1"
name = "Batch Script Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.nanoserver-2022"
