# Buildpack API version
api = "0.10"

# Buildpack ID and metadata
[buildpack]
id = "samples/batch-script"
version = "0.0.1"
name = "Batch Script Buildpack"

# Targets the buildpack will work with
[[targets]]
os = "windows"
[[targets.distros]]
version = "10.0.20348.1906"

# Stacks (deprecated) the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.nanoserver-2022"
