# Buildpacks to include in builder
[[buildpacks]]
id = "samples/dotnet-framework"
version = "0.0.1"
uri = "../../buildpacks/dotnet-framework"

# Order used for detection
[[order]]
[[order.group]]
id = "samples/dotnet-framework"
version = "0.0.1"

# Images that will be used by the builder
[build]
image = "cnbs/sample-img-build:dotnet-framework-2004"


[run]
[[run.images]]
image = "cnbs/sample-img-run:dotnet-framework-2004"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.samples.stacks.dotnet-framework-2004"
run-image = "cnbs/sample-stack-run:dotnet-framework-2004"
build-image = "cnbs/sample-stack-build:dotnet-framework-2004"
