# Buildpacks to include in builder
[[buildpacks]]
id = "samples/dotnet-framework"
version = "0.0.1"
uri = "../../buildpacks/dotnet-framework"

# Order used for detection
[[order]]
[[order.group]]
id = "samples/dotnet-framework"
version = "0.0.1"

# Images that will be used by the builder
[build]
image = "cnbs/sample-img-build:dotnet-framework-2022""


[run]
[[run.images]]
image = "cnbs/sample-img-run:dotnet-framework-2022""

