# Buildpacks to include in builder
[[buildpacks]]
id = "samples/dotnet-framework"
version = "0.0.1"
uri = "../../buildpacks/dotnet-framework"

# Order used for detection
[[order]]
[[order.group]]
id = "samples/dotnet-framework"
version = "0.0.1"

# Base images used to create the builder
[build]
image = "cnbs/sample-base-build:dotnet-framework-2022"
[run]
[[run.images]]
image = "cnbs/sample-base-run:dotnet-framework-2022"

# Stack (deprecated) used to create the builder
[stack]
id = "io.buildpacks.samples.stacks.dotnet-framework-2022"
build-image = "cnbs/sample-base-build:dotnet-framework-2022"
run-image = "cnbs/sample-base-run:dotnet-framework-2022"
